IOS-1695 Don't show error at the first scan card with access code
tangem/tangem-sdk-ios pull request #188
Opened 2022-06-02 12:10 UTC by Balashov152

2022-06-03 12:59 UTC, tureck1y requested changes

2022-06-03 12:59 UTC, tureck1y commented on TangemSdk/TangemSdk/Operations/Command.swift
> +                session.pause(message: "error_pin_required_format".localized(UserCodeType.accessCode.name))
```suggestion
                session.pause(message: sdkError.localizedDescription)
```

2022-06-06 08:46 UTC, Balashov152 commented on TangemSdk/TangemSdk/Operations/Command.swift
> +                session.pause(message: "error_pin_required_format".localized(UserCodeType.accessCode.name))
Сделал одну логику для accessCode и passcode
Для `message` использовал `sdkError.localizedDescription` ✅

2022-06-06 08:55 UTC, tureck1y commented on TangemSdk/TangemSdk/Operations/Command.swift
> +        case .accessCodeRequired:
passcodeRequired сюда еще

2022-06-09 09:06 UTC, tureck1y commented on TangemSdk/TangemSdk/Operations/Command.swift
> +        case .accessCodeRequired:
@Balashov152

2022-06-10 12:17 UTC, Balashov152 commented on TangemSdk/TangemSdk/Operations/Command.swift
> +        case .accessCodeRequired:
поправил, что то уведомление не пришло(

2022-06-10 12:25 UTC, tureck1y approved these changes

2022-06-10 12:29 UTC, gre4ixin approved these changes

2022-06-13 04:50 UTC, megakoko approved these changes

2022-06-14 09:26 UTC, lazutkin-andrey approved these changes

2022-06-20 14:07 UTC, merged