Css 130 advanced usage update readme
tangem/tangem-sdk-ios pull request #20
Opened 2021-04-29 08:56 UTC by Andoran90

2021-04-29 15:54 UTC, lazutkin-andrey requested changes
В тексте есть неточности

2021-05-06 08:46 UTC, lazutkin-andrey approved these changes

2021-05-06 09:25 UTC, tureck1y commented on README.md
>  Then run `pod install`.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>TAG</string>
	</array>
</dict>
</plist>

```
Есть один нюанс. Когда добавляешь nfc tag capability, автоматически создается запись в entitlements c ndef и tag. Так вот ndef нужно удалять вручную, иначе при заливке в стор будет ошибка. Надо бы это добавить. Выше как раз вид entitlements файла, каким он должен быть

2021-05-06 11:17 UTC, tureck1y approved these changes

2021-05-06 11:37 UTC, lazutkin-andrey approved these changes

2021-05-06 11:37 UTC, merged