CSS-139 JSON-RPC
tangem/tangem-sdk-ios pull request #35
Opened 2021-05-21 20:22 UTC by tureck1y

2021-05-24 12:50 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Common/CardSession.swift
> +                jsonCore: JSONRPCCore) {
Каждое следующее название хуже педыдущего :)
Его задача преобразовать JSON в Runnable. Тогда может так:
```suggestion
                jsonTransformer: JSONRPCTransformer) {
```

2021-05-24 15:28 UTC, Andoran90 requested changes

2021-05-24 15:28 UTC, Andoran90 commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +public class JSONRPCConverter {
может сделать его final?

2021-05-24 15:28 UTC, Andoran90 commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +extension SignCommand: JSONRPCConvertible {
остальные команды позже будем добавлять?

2021-05-24 20:09 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +            return JSONRPCError(.serverError, data: sdkError.localizedDescription)
JSONRPCError соответствует спецификации json-rpc, в которой прописаны типы ошибок и их коды. В этой ошибке предусмотрено дополнительное поле для лююой полезной инфы, туда кладем нашу внутреннюю ошибку.

2021-05-24 20:10 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +}
Вся реализация json-rpc пока в одном файле для наглядности и удобства разработки и рефакторинга, позже можно будет либо все в один файл положить, либо уже по командам рассовать. Если бы не рефакторинг сдк, пришлось бы ревьювить условно один файл

2021-05-24 20:22 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +                }
Строго говоря у меня реализация не до конца правильная. В 2.0 мы должны поддерживать и просто массив неименованных параметров из версии 1.0, но это не ложится на сдк вообще, потому что неясно как это парсить дальше и как вытаскивать нужные нам параметры. 
@lazutkin-andrey Что думаешь?

2021-05-24 20:22 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONStringConvertible.swift
>          encoder.outputFormatting = [.sortedKeys, .prettyPrinted]
Я тут еще ослабил требование к респонсу, иначе AnyResponse не получалось сделать

2021-05-24 20:25 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +        } catch {
Про ошибку не очень понял, тут же везде через try-catch. Ошибка с любого уровня прикидывается насквозь, либо ты что-то другое имел в виду?

Мне кажется через params ходить все же нагляднее, можно конечно продублировать оба метода из extension'a для словаря. 
@lazutkin-andrey мнение?

2021-05-24 20:28 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +public class JSONRPCConverter {
В принципе можно, но этого вроде как ничего не даст. В сдк его не подменить никак, он приватный, можно наверное вообще приватным сделать

2021-05-24 20:29 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +extension SignCommand: JSONRPCConvertible {
Ага, еще впереди много работы, это лишь каркас. Нужно больше тестов

2021-05-25 05:18 UTC, Andoran90 commented on TangemSdk/TangemSdk/TangemSdk.swift
> +        } catch {
ну в смысле на перспективу можно будет сделать что-то типа:
``` swift
func value<T>(for key: String) throws -> T where T: Equatable, T: Decodable {
    // ну или тут делать проверки на кастомные сообщение initialMessage и подменять своим
    do {
        try params.value(for: key)
    } catch {
        // Error handling and custom logic
    }
}
```

но это так, размышления на счет ошибки.
А на счет наглядности - в целом никто же не запрещает через словарь обращаться, просто более короткая альтернатива

2021-05-25 05:22 UTC, Andoran90 commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +public class JSONRPCConverter {
мммм, тесты же тогда не получится делать

2021-05-25 07:47 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +public class JSONRPCConverter {
@testable import нам поможет

2021-05-25 08:34 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +        } catch {
Логики тут точно не будет, это же просто словарь из которого мы дергаем параметры. Я не очень люблю когда одинаковый код  можно вызвать по-разному, поэтому я бы не стал этого делать, будет чище. Более того, тебе даже нигде это писаться придется.  В команды уже приходят params, а единственное место где нужно пройти полный путь - вытащить initial message и cid в TangemSdk, что уже написано)

2021-05-25 19:25 UTC, gbixahue commented on TangemSdk/TangemSdk/Tasks/PreflightReadTask.swift
> +    case none
wiil -> will

2021-05-26 07:00 UTC, gbixahue approved these changes

2021-05-26 07:38 UTC, gbixahue requested changes
1) CardSessionRunnable теперь не имеет requiresPin2, следовательно и все кастомные таски его также утратили. 
2) Т.к. PreflightReadCapable.needPreflightRead() был заменен на PreflightReadMode, то в командах: DepersonalizeCommand, ReadCommand, ReadWalletCommand, ReadWalletListCommand нужно проставить соответствующие значения.

2021-05-26 07:58 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Common/JSONRPC.swift
> +                }
я думаю проверять конкретно версию нет смысла, по крайней мере я чет не вижу кейса, как это может кому-то помочь или предотвратить беду, с другой стороны проставлять 2.0 тоже странно)
Я что-то не заметил, а возвращаем ли мы ID запроса в ответе или ошибке?

2021-05-26 09:58 UTC, Andoran90 requested changes

2021-05-26 09:58 UTC, Andoran90 commented on TangemSdk/TangemSdk/TangemSdk.swift
> +            }
```suggestion
        var request: JSONRPCRequest!
        do {
            request = try JSONRPCRequest(jsonString: jsonRequest)
            try checkSession()
            let runnable = try jsonConverter.convert(request: request)
            configure()
            cardSession = makeSession(with: try request.params.value(for: "cid"),
                                      initialMessage: try request.params.value(for: "initialMessage"))
            cardSession!.start(with: runnable) { completion($0.toJsonResponse(id: request.id).json) }
        } catch {
            completion(error.toJsonResponse(id: request?.id).json)
            return
        }
```

2021-05-26 10:46 UTC, Andoran90 approved these changes

2021-05-26 10:47 UTC, gbixahue approved these changes

2021-05-26 11:36 UTC, lazutkin-andrey approved these changes

2021-05-26 13:09 UTC, merged

2021-05-26 19:54 UTC, gbixahue commented
Будем приводить JSONRPC.id к Any?
{"jsonrpc": "2.0", "method": "subtract", "params": {}, "id": 1}
{"jsonrpc": "2.0", "method": "subtract", "params": {}, "id": "1"}
{"jsonrpc": "2.0", "method": "subtract", "params": {}}