Response separation
tangem/tangem-sdk-ios pull request #40
Opened 2021-06-02 11:29 UTC by tureck1y

2021-06-02 11:59 UTC, lazutkin-andrey submitted a review, later dismissed

2021-06-03 07:16 UTC, Andoran90 requested changes

2021-06-03 07:16 UTC, Andoran90 commented on TangemSdk/TangemSdk/Commands/Command.swift
> +
А зачем поменяли порядок функций? было же правильно: публичные, внутренние, приватные, а сейчас разнобой стал

2021-06-03 07:16 UTC, Andoran90 commented on TangemSdk/TangemSdk/Commands/Command.swift
> +
я не помню, есть ли где-то файлик с гайдами по оформлению кода?

2021-06-03 07:18 UTC, Andoran90 commented
В файлах ReadWalletCommand и ReadWalletListCommand не добавили typealias Response + там в респонсах cid, вместо cardId

2021-06-03 08:11 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/Command.swift
> +
Случайно) Ща обновлю

2021-06-03 08:14 UTC, tureck1y commented
cid на cardId я поменял в другом PR, который сейчас делаю. А typealias  в общем-то необязательная штука. Можно везде потереть или везде оставить, не решил пока

2021-06-03 08:16 UTC, Andoran90 approved these changes

2021-06-03 10:02 UTC, lazutkin-andrey approved these changes

2021-06-03 10:03 UTC, merged