CSS-121 array of hashes
Tangem/tangem-sdk-ios pull request #6
Opened 2021-04-06 13:19 UTC by Andoran90

2021-04-06 16:24 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Чет не понимаю, почему это попало в этот PR?

2021-04-06 16:30 UTC, lazutkin-andrey commented on Example/TangemSdkExample/ViewController.swift
> +        let hash = getRandomHash()
тестовый коммент

2021-04-07 07:28 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
responses - не используется, можно потереть
respondedSignature - может просто signature?

2021-04-07 07:29 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +                let parsed = try SignatureParser.parseSignedSignature(respondedSignature)
SignatureParser - насколько нам вообще нужна отдельная утилита? Кроме как здесь больше нигде не используется же. Ну и parse мне кажется тоже не отражает смысла. Chunked, sliced и тп на мой взгляд лучше подходят

2021-04-07 07:31 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/Wallet/PurgeWalletCommand.swift
> +            walletIndex: .index(try decoder.decode(.walletIndex)))
Для старых кард проблем не будет?

2021-04-07 07:35 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/TangemSdkError.swift
> +    case notValidSignedSignatureSize
А надо ли добавлять такую ошибку? Я бы бил не по 64 байта, а по количеству хешей, которые пришли на вход команде sign, прям внутри команды sign. По идее там ошибки быть вообще не может

2021-04-07 07:41 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> -    ///   - onlineVerification: Verify the card offline and online with Tangem backend. Do not use for developer cards
Про онлайн верификацию для релизных карт надо бы дописать

2021-04-07 07:42 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +                guard signatures.count == 1 else {
это надо порешать внутри sign. Такой ошибки быть не может в принципе

2021-04-07 07:43 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func sign(cardId: String? = nil,
И тут и в предыдущей команде sign нужно поменять местами аргументы. Sign hash, sign hashes. Сейчас плохо - sign cardId, который опциональный вообще

2021-04-07 07:46 UTC, Andoran90 commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +                let parsed = try SignatureParser.parseSignedSignature(respondedSignature)
вынес чтобы не было слишком много функционала в команде, она итак довольно раздутая получилась, по yagni, конечно лишнее

2021-04-07 07:49 UTC, Andoran90 commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func sign(cardId: String? = nil,
> И тут и в предыдущей команде sign нужно поменять местами аргументы. Sign hash, sign hashes. Сейчас плохо - sign cardId, который опциональный вообще

меняли специально местами, чтобы везде в начале был cardId, чтобы однообразие было в командах. Если сдвигать, тогда лучше везде сдвинуть перед initialMessage, а не только в одном месте

2021-04-07 07:56 UTC, tureck1y requested changes

2021-04-07 07:56 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func purgeWallet(cardId: String? = nil,
то же самое. Опциональные параметры впереди обязательных

2021-04-07 07:56 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func purgeWallet(cardId: String? = nil,
Для остальных команд не буду копипастить коммент, надо по всем пробежаться аккуратно и не забыть коммент поправить

2021-04-07 07:58 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func sign(cardId: String? = nil,
Ну зря вы это сделали. Тут и было однообразие и по гайдам. Сначала значимый аргумент, потом все необязательный в одинаковом порядке.

2021-04-07 08:03 UTC, Andoran90 commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func sign(cardId: String? = nil,
> Ну зря вы это сделали. Тут и было однообразие и по гайдам. Сначала значимый аргумент, потом все необязательный в одинаковом порядке.

в том то и проблема, что и раньше было в разнобой и неправильно, всегда в начале держался cardId. Я тогда просто уберу cardId перед initialMessage, чтобы в начале всегда были только параметры команды основные, а потом уже связанное с карточкой.

2021-04-07 08:12 UTC, tureck1y commented on TangemSdk/TangemSdk/TangemSdk.swift
> +    public func sign(cardId: String? = nil,
Да, ты прав, это копипаст из Андроида, отсюда и расхождение. Согласен с тем что ты написал, раз уж рефрактором то делаем сразу правильно

2021-04-07 09:17 UTC, Andoran90 commented on TangemSdk/TangemSdk/Commands/Wallet/PurgeWalletCommand.swift
> +            walletIndex: .index(try decoder.decode(.walletIndex)))
да, ты прав, будет, тупанул... сейчас исправлю

2021-04-07 10:49 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Чем дальше в лес, тем дольше выходить. 
Чем плоха логика типа:
Имеем два массива hashes, signatures
Ну грубо говоря
if (hashes.count > signatures.count) {
 sign(hashes.sub(signatures.count, chunkSize))
} else {
// Берем респонс, засовываем туда все подписи и возвращаем.
}

Зачем все эти канутеры, сохранение респонсов, последний респонс

2021-04-07 10:49 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +                let parsed = try SignatureParser.parseSignedSignature(respondedSignature)
+1 не надо выносить, если не будем переиспользовать, отдельный метод - ок.

2021-04-07 10:49 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +                                walletRemainingSignatures: try decoder.decodeOptional(.walletRemainingSignatures) ?? 99999, // In COS v.4.0 remaining signatures was removed
Ну сделайте тогда его опциональным. Зачем 999999?

2021-04-07 10:49 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Common/TangemSdkError.swift
> +    case notValidSignedSignatureSize
+1 что 64 байта это потенциальный баг, а если на какой-то кривой будет 128 байт подпись. SDK ничего не должно знать про это.

2021-04-07 10:56 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Ну раньше у меня тут лежал массив всех респонсов, из которых я собирал финальный, так было вроде понятнее немного. Каунтеры нужны для правильного нарезания, если я верно понял

2021-04-07 10:59 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Можно же обойтись, станет чище и понятнее.

2021-04-07 11:02 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Ты рекурсию предлагаешь?

2021-04-07 11:05 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Не понял вопроса, сейчас уже сделано с рекурсией. Sign вызывает сам себя в колбеке от трансива.

2021-04-07 11:07 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Ну либо хранение респонсов либо рекурсивно их передавать вовнутрь. Ты кажется забыл для чего этот код используется. Это нужно для подписи большого количества хэшей

2021-04-07 11:39 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
Обсудили по телеофону.
Я предлагаю избавиться от
lastSignResponse, respon**c**es, respondedSignature, currentChunk, numberOfChunks.

Еще раз, я вижу логику так:
1. В начале имеем два массива, хешей и подписей. Массив подписей изначально пустой.
2. Берем кусочек массива хэшей, согласно chunkSize или весь массив, если его количество меньше   chunkSize и дергаем метод Sign
3. В методе Sign Обновляем статус ViewDelegate, вычисляя количество итераций и текущую итерацию и делаем transieve.
4. Как только получен ответ, добавляем полученные подписи в массив подписей, проверяем количество хэшей и подписей. Если количество хэшей равно количеству подписей, значит все ок, берем только что вернувшийся response, подменяем в нем массив подписей на "полный" и отдаем success, если нет – делаем переходим к пункту (2), только для рассмотрения берем массив исключая уже подписанные хэши.

2021-04-07 11:40 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
`    func sign(in session: CardSession, completion: @escaping CompletionResult<SignResponse>) {
        if numberOfChunks > 1 {
            session.viewDelegate.showAlertMessage("Signing part \(currentChunk + 1) of \(numberOfChunks)")
        }
        
        transieve(in: session) { result in
            switch result {
            case .success(let response):
                self.respondedSignature += response.signatures.joined()
                self.currentChunk += 1
                if self.currentChunk == self.numberOfChunks {
                    do {
                        let parsed = try SignatureParser.parseSignedSignature(self.respondedSignature)
                        completion(.success(SignResponse(cardId: response.cardId,
                                                         signatures: parsed,
                                                         walletRemainingSignatures: response.walletRemainingSignatures,
                                                         walletSignedHashes: response.walletSignedHashes)))
                        return
                    } catch {
                        completion(.failure(error as! TangemSdkError))
                        return
                    }
                } else {
                    if self.currentChunk != self.numberOfChunks {
                        session.restartPolling()
                    }
                    self.sign(in: session, completion: completion)
                }
              
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }`
    
   Предлагаю сделать так, чтобы выкинуть lastresponse. Способа выкинуть currentChunk я не вижу в текущей реализации. У нас нет информации сколько хешей подписано

2021-04-07 11:49 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var respondedSignature: Data = Data()
@tureck1y

2021-04-07 14:42 UTC, lazutkin-andrey commented
@Andoran90, еще надо не забыть примеры в readme.md поправить.

2021-04-07 14:57 UTC, Andoran90 commented on TangemSdk/TangemSdk/Common/TangemSdkError.swift
> +    case notValidSignedSignatureSize
ок, а если карточка на 2 подписи ответила не 128, а 125? Это же просто дополнительная проверка, что карточка дала адекватный ответ, а если внезапно придет неправильные данные, тогда и приложение не упадет и не останутся какие-то лишние куски. Зависимость от 64 убрал. Если считаете, что проверка не нужна дополнительная, то ок, уберу

2021-04-07 15:00 UTC, tureck1y commented on TangemSdk/TangemSdk/Common/TangemSdkError.swift
> +    case notValidSignedSignatureSize
Насколько я понимаю, карта не может вернуть ничего такого, а чтобы в коде место заткнуть, можно просто заюзать какую-нибудь дженериковую ошибку, типа cardError. А новая ошибка - это новые коды, текстовки - слишком жирно для невозможной ошибки

2021-04-08 04:55 UTC, Andoran90 commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var lastChunkNumber: Int {
ну lastChunkNumber все же по смыслу больше подходит, последний чанк, который уже обработан. В getChunk мы отталкиваемся же не от текущего, а от последнего. Или currentChunkIndex.

2021-04-08 05:55 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/TangemSdk.swift
> +                guard signatures.count == 1 else {
+1

2021-04-08 05:56 UTC, lazutkin-andrey commented on TangemSdk/TangemSdk/Common/Utilities/SignatureParser.swift
> +enum SignatureParser {
Мы же вроде хотели отказаться от отдельного класса?

2021-04-08 05:59 UTC, Andoran90 commented on TangemSdk/TangemSdk/Common/Utilities/SignatureParser.swift
> +enum SignatureParser {
> Мы же вроде хотели отказаться от отдельного класса?

так его и нет, я его удалил. Outdated

2021-04-08 09:02 UTC, tureck1y commented on TangemSdk/TangemSdk/Commands/SignCommand.swift
> +    private var lastChunkNumber: Int {
+1 за currentChunkNumber или currentChunk как было

2021-04-08 09:45 UTC, tureck1y approved these changes

2021-04-08 09:45 UTC, lazutkin-andrey approved these changes

2021-04-08 09:49 UTC, merged